const char* MQTT_SERVER_LOGIN = AWRURA_MQTT_SERVER_LOGIN;
const char* MQTT_SERVER_PASS = AWRURA_MQTT_SERVER_PASS;
const char* MQTT_SERVER_IP = AWRURA_MQTT_SERVER_IP;
const char* TOPIC = AWRURA_TOPIC;
const char* CLIENT_UUID = AWRURA_CLIENT_UUID;
const char* WIFI_SSID = AWRURA_WIFI_SSID;
const char* WIFI_PASS = AWRURA_WIFI_PASS;
const int MQTT_SERVER_PORT = AWRURA_MQTT_SERVER_PORT;
